### ISSUE TITLE
The account being accessed does not support http

### ISSUE THREAD

**Issue by afranioce** [JetBrains/teamcity-azure-agent#112]
## Description

Is hosted using valid https certificate

## Environment

* TeamCity version: TeamCity Professional 2018.2.3 (build 61544)
* Azure plugin version: 0.8.9

### teamcity-clouds.log
```
[2019-03-20 13:05:21,154]   INFO [uled executor 5] - .server.impl.CloudEventsLogger - Cloud instance has gone (is not reported by cloud profile): profileId=arm-3, imageId=jetbrains-teamcity-agent, instanceId=jetbrains-teamcity-agent1
[2019-03-20 13:05:21,364]   INFO [1 Flush Queue 1] - .instances.StartInstanceAction - Starting cloud instance: profile 'Azure'{id=arm-3, projectId=_Root}, AzureCloudImage{myName='jetbrains-teamcity-agent'}, hash=hjb2HEShrSEn6znSPIAjfcHK30aZAPQI, reason=Automatic start: Start instance to get instance agent details
[2019-03-20 13:05:21,365]   INFO [1 Flush Queue 1] - uds.base.AbstractCloudInstance - Changing jetbrains-teamcity-agent1(42caf691) status from Unknown to Scheduled to start 
[2019-03-20 13:05:21,365]   INFO [atcher-worker-6] - ouds.azure.arm.AzureCloudImage - Creating new virtual machine jetbrains-teamcity-agent1
[2019-03-20 13:05:21,365]   INFO [1 Flush Queue 1] - .server.impl.CloudEventsLogger - Cloud instance entered 'scheduled to start' state, profile 'Azure'{id=arm-3, projectId=_Root}, AzureCloudInstance{myName='jetbrains-teamcity-agent1'}
[2019-03-20 13:05:21,365]   INFO [1 Flush Queue 1] - .server.impl.CloudEventsLogger - Cloud instance start succeeded: profile 'Azure'{id=arm-3, projectId=_Root}, AzureCloudInstance{myName='jetbrains-teamcity-agent1'}
[2019-03-20 13:05:21,651]   WARN [atcher-worker-3] - ouds.azure.arm.AzureCloudImage - The account being accessed does not support http.: com.microsoft.azure.storage.StorageException: The account being accessed does not support http. (enable debug to see stacktrace)
[2019-03-20 13:05:21,651]   INFO [atcher-worker-3] - uds.base.AbstractCloudInstance - Changing jetbrains-teamcity-agent1(42caf691) status from Scheduled to start to Error 
[2019-03-20 13:05:21,651]   INFO [atcher-worker-3] - ouds.azure.arm.AzureCloudImage - Removing allocated resources for virtual machine jetbrains-teamcity-agent1
[2019-03-20 13:05:21,751]   INFO [atcher-worker-4] - ouds.azure.arm.AzureCloudImage - Allocated resources for virtual machine jetbrains-teamcity-agent1 have been removed
[2019-03-20 13:05:21,868]   INFO [1 Flush Queue 1] - .instances.StartInstanceAction - Starting cloud instance: profile 'Azure'{id=arm-3, projectId=_Root}, AzureCloudImage{myName='jetbrains-teamcity-agent'}, hash=ZhWlhfcrZNXk4zrcHN0RHgx7zmq5CP0m, reason=Automatic start: Start instance to get instance agent details
[2019-03-20 13:05:21,868]   INFO [1 Flush Queue 1] - uds.base.AbstractCloudInstance - Changing jetbrains-teamcity-agent1(542e85fd) status from Unknown to Scheduled to start 
[2019-03-20 13:05:21,868]   INFO [atcher-worker-2] - ouds.azure.arm.AzureCloudImage - Creating new virtual machine jetbrains-teamcity-agent1
[2019-03-20 13:05:21,868]   INFO [1 Flush Queue 1] - .server.impl.CloudEventsLogger - Cloud instance start succeeded: profile 'Azure'{id=arm-3, projectId=_Root}, AzureCloudInstance{myName='jetbrains-teamcity-agent1'}
[2019-03-20 13:05:22,167]   WARN [atcher-worker-4] - ouds.azure.arm.AzureCloudImage - The account being accessed does not support http.: com.microsoft.azure.storage.StorageException: The account being accessed does not support http. (enable debug to see stacktrace)
[2019-03-20 13:05:22,167]   INFO [atcher-worker-4] - uds.base.AbstractCloudInstance - Changing jetbrains-teamcity-agent1(542e85fd) status from Scheduled to start to Error 
[2019-03-20 13:05:22,167]   INFO [atcher-worker-4] - ouds.azure.arm.AzureCloudImage - Removing allocated resources for virtual machine jetbrains-teamcity-agent1
[2019-03-20 13:05:22,211]   INFO [atcher-worker-5] - ouds.azure.arm.AzureCloudImage - Allocated resources for virtual machine jetbrains-teamcity-agent1 have been removed
[2019-03-20 13:05:22,371]   INFO [2 Flush Queue 1] - .instances.StartInstanceAction - Starting cloud instance: profile 'Azure'{id=arm-3, projectId=_Root}, AzureCloudImage{myName='jetbrains-teamcity-agent'}, hash=PWTiK2xPnApMkUncCNBZSiKoc6TTML9j, reason=Automatic start: Start instance to get instance agent details
[2019-03-20 13:05:22,371]   INFO [2 Flush Queue 1] - uds.base.AbstractCloudInstance - Changing jetbrains-teamcity-agent1(5e3fc875) status from Unknown to Scheduled to start 
[2019-03-20 13:05:22,371]   INFO [2 Flush Queue 1] - .server.impl.CloudEventsLogger - Cloud instance start succeeded: profile 'Azure'{id=arm-3, projectId=_Root}, AzureCloudInstance{myName='jetbrains-teamcity-agent1'}
[2019-03-20 13:05:22,371]   INFO [atcher-worker-2] - ouds.azure.arm.AzureCloudImage - Creating new virtual machine jetbrains-teamcity-agent1
[2019-03-20 13:05:22,655]   WARN [atcher-worker-1] - ouds.azure.arm.AzureCloudImage - The account being accessed does not support http.: com.microsoft.azure.storage.StorageException: The account being accessed does not support http. (enable debug to see stacktrace)
[2019-03-20 13:05:22,655]   INFO [atcher-worker-1] - uds.base.AbstractCloudInstance - Changing jetbrains-teamcity-agent1(5e3fc875) status from Scheduled to start to Error 
[2019-03-20 13:05:22,655]   INFO [atcher-worker-1] - ouds.azure.arm.AzureCloudImage - Removing allocated resources for virtual machine jetbrains-teamcity-agent1
[2019-03-20 13:05:22,673]   INFO [atcher-worker-5] - ouds.azure.arm.AzureCloudImage - Allocated resources for virtual machine jetbrains-teamcity-agent1 have been removed
[2019-03-20 13:05:22,874]   INFO [2 Flush Queue 1] - .instances.StartInstanceAction - Starting cloud instance: profile 'Azure'{id=arm-3, projectId=_Root}, AzureCloudImage{myName='jetbrains-teamcity-agent'}, hash=6fGUUzxLLEaqUEPygcOrvOawZ91ebKMm, reason=Automatic start: Start instance to get instance agent details
[2019-03-20 13:05:22,874]   INFO [2 Flush Queue 1] - uds.base.AbstractCloudInstance - Changing jetbrains-teamcity-agent1(639a458f) status from Unknown to Scheduled to start 
[2019-03-20 13:05:22,874]   INFO [atcher-worker-5] - ouds.azure.arm.AzureCloudImage - Creating new virtual machine jetbrains-teamcity-agent1
[2019-03-20 13:05:22,874]   INFO [2 Flush Queue 1] - .server.impl.CloudEventsLogger - Cloud instance start succeeded: profile 'Azure'{id=arm-3, projectId=_Root}, AzureCloudInstance{myName='jetbrains-teamcity-agent1'}
[2019-03-20 13:05:23,167]   WARN [atcher-worker-5] - ouds.azure.arm.AzureCloudImage - The account being accessed does not support http.: com.microsoft.azure.storage.StorageException: The account being accessed does not support http. (enable debug to see stacktrace)
[2019-03-20 13:05:23,167]   INFO [atcher-worker-5] - uds.base.AbstractCloudInstance - Changing jetbrains-teamcity-agent1(639a458f) status from Scheduled to start to Error 
[2019-03-20 13:05:23,167]   INFO [atcher-worker-5] - ouds.azure.arm.AzureCloudImage - Removing allocated resources for virtual machine jetbrains-teamcity-agent1
[2019-03-20 13:05:23,185]   INFO [atcher-worker-5] - ouds.azure.arm.AzureCloudImage - Allocated resources for virtual machine jetbrains-teamcity-agent1 have been removed
[2019-03-20 13:05:23,377]   INFO [3 Flush Queue 1] - .instances.StartInstanceAction - Starting cloud instance: profile 'Azure'{id=arm-3, projectId=_Root}, AzureCloudImage{myName='jetbrains-teamcity-agent'}, hash=0zJCAAPdLAL4B9RjVbJONOECQd7ChpUU, reason=Automatic start: Start instance to get instance agent details
[2019-03-20 13:05:23,377]   INFO [3 Flush Queue 1] - uds.base.AbstractCloudInstance - Changing jetbrains-teamcity-agent1(2e70de0d) status from Unknown to Scheduled to start 
[2019-03-20 13:05:23,377]   INFO [atcher-worker-2] - ouds.azure.arm.AzureCloudImage - Creating new virtual machine jetbrains-teamcity-agent1
[2019-03-20 13:05:23,377]   INFO [3 Flush Queue 1] - .server.impl.CloudEventsLogger - Cloud instance start succeeded: profile 'Azure'{id=arm-3, projectId=_Root}, AzureCloudInstance{myName='jetbrains-teamcity-agent1'}
```

### stacktrace
```
om.microsoft.azure.storage.StorageException: The account being accessed does not support http.com.microsoft.azure.storage.StorageException: The account being accessed does not support http.
at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87)
at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:315)
at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:185)
at com.microsoft.azure.storage.file.CloudFileShare.exists(CloudFileShare.java:986)
at com.microsoft.azure.storage.file.CloudFileShare.createIfNotExists(CloudFileShare.java:314)
at com.microsoft.azure.storage.file.CloudFileShare.createIfNotExists(CloudFileShare.java:290)
at jetbrains.buildServer.clouds.azure.arm.connector.AzureApiConnectorImpl$addContainerCustomData$2.invokeSuspend(AzureApiConnectorImpl.kt:639)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
at kotlinx.coroutines.ResumeModeKt.resumeUninterceptedMode(ResumeMode.kt:45)
at kotlinx.coroutines.internal.ScopeCoroutine.onCompletionInternal$kotlinx_coroutines_core(Scopes.kt:25)
at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:299)
at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:258)
at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:755)
at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:735)
at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:117)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:45)
at kotlinx.coroutines.ResumeModeKt.resumeUninterceptedMode(ResumeMode.kt:45)
at kotlinx.coroutines.internal.ScopeCoroutine.onCompletionInternal$kotlinx_coroutines_core(Scopes.kt:25)
at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:299)
at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:258)
at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:755)
at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:735)
at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:117)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:45)
at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) 
```

**Comment by dtretyakov** [comment]
@afranioce, thanks for reporting. Please update to the latest plugin version: https://plugins.jetbrains.com/plugin/9260-azure-resource-manager-cloud-support
