### ISSUE TITLE
Maming prefix length limit incorrect for Azure Storage

### ISSUE THREAD

**Issue by rocketraman** [JetBrains/teamcity-azure-agent#116]
## Description

My naming prefix defaulted to a long value, and it was too long for Azure Storage. I was getting these logs in `teamcity-cloud.log`:

```
[2019-08-29 00:23:00,695]   INFO [atcher-worker-1] - ouds.azure.arm.AzureCloudImage - Virtual machine xxxxxxcr-azurecr-io-xxxxxx-teamcity-agent-2019-1-2-linux1 has been successfully terminated
[2019-08-29 00:23:00,710]   WARN [atcher-worker-4] - ouds.azure.arm.AzureCloudImage - The specified resource name length is not within the permissible limits.: com.microsoft.azure.storage.StorageException: The specified resource name length is not within the permissible limits.
[2019-08-29 00:23:00,711]  DEBUG [atcher-worker-4] - ouds.azure.arm.AzureCloudImage - The specified resource name length is not within the permissible limits.
com.microsoft.azure.storage.StorageException: The specified resource name length is not within the permissible limits.
        at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87)
        at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:315)
        at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:185)
        at com.microsoft.azure.storage.file.CloudFileShare.exists(CloudFileShare.java:986)
        at com.microsoft.azure.storage.file.CloudFileShare.createIfNotExists(CloudFileShare.java:314)
        at com.microsoft.azure.storage.file.CloudFileShare.createIfNotExists(CloudFileShare.java:290)
        at jetbrains.buildServer.clouds.azure.arm.connector.AzureApiConnectorImpl$addContainerCustomData$2.invokeSuspend(AzureApiConnectorImpl.kt:645)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.ResumeModeKt.resumeUninterceptedMode(ResumeMode.kt:45)
        at kotlinx.coroutines.internal.ScopeCoroutine.onCompletionInternal$kotlinx_coroutines_core(Scopes.kt:25)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:299)
        at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:258)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:755)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:735)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:117)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:45)
        at kotlinx.coroutines.ResumeModeKt.resumeUninterceptedMode(ResumeMode.kt:45)
        at kotlinx.coroutines.internal.ScopeCoroutine.onCompletionInternal$kotlinx_coroutines_core(Scopes.kt:25)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:299)
        at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:258)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:755)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:735)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:117)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:45)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

Perhaps when the storage is enabled, the max name prefix length needs to be shorter.

## Environment

* TeamCity version: 2019.1.2
* Azure plugin version: 0.9.0

## Diagnostic logs

See above.

**Comment by dimyriy** [comment]
@rocketraman Issue has been moved to JetBrains YouTrack. Please, follow the issue https://youtrack.jetbrains.com/issue/TW-61940 for updates.
